# Site settings
title:          Lalu
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:            moseory.github.io
# Author
author:
  name:         Lalu Kim
  email:        deepdeep.moho@gmail.com
  url:          

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: deepdeep.moho@gmail.com
  github: https://moseory.github.io/
